### ISSUE TITLE
migration failed with error: The query is empty

### ISSUE THREAD

**Issue by jschenke488** [degabut/degabut#1]
I'm trying to run Degabut using Docker, but the dgb-default container is crashing in a loop with this error. This is the first time I'm running the bot.
![image](https://github.com/degabut/degabut/assets/44783760/d0d1e4cd-34b4-4fa8-8bf0-a7a7667c25f2)

**Comment by SuspiciousLookingOwl** [comment]
Fixed on https://github.com/degabut/degabut/commit/bbaa3b4903275456050ef87ca05f2e79101d8173. Please update to `4.1.11`

Thank you!

**Comment by jschenke488** [comment]
Works as expected now, thank you
