### ISSUE TITLE
Track load failed loadType=NO_MATCHES tracks=[] playlistInfo={}

### ISSUE THREAD

**Issue by ri1ongithub** [degabut/degabut#4]
When I try to play music (using /play command or via the web ui), the music doesn't play.

Bot's console output :
```
Track load failed loadType=NO_MATCHES tracks=[] playlistInfo={}
```

Lavalink's console output : 
```
l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "[VIDEO ID]"
lavalink.server.player.AudioLoader       : No matches found
```

Could be related to https://github.com/sedmelluq/lavaplayer/issues/694

Thank You.

**Comment by SuspiciousLookingOwl** [comment]
I'm not sure what's causing this, but it seems like it's caused by lavalink. 

Do you have a video id example to reproduce this? Is the video private or perhaps age restricted?

**Comment by ri1ongithub** [comment]
It does this with every video, I tried with Never Gonna Give You Up and some French songs

**Comment by SuspiciousLookingOwl** [comment]
Have you tried using the new `youtube-source` plugin for Lavalink?
https://github.com/lavalink-devs/youtube-source?tab=readme-ov-file#plugin

**Comment by ri1ongithub** [comment]
Yes, I also tried other versions of lavalink

**Comment by SuspiciousLookingOwl** [comment]
Seems like an issue with lavalink, I couldn't replicate this issue, you can try going to their Discord and ask for some help there as it's out of this project's scope

**Comment by ri1ongithub** [comment]
I resolved it by adding the LavaSrc plugin (and youtube-plugin) to lavalink

Thank you
